# Main system configuration for ROCK5 ITX
{
  config,
  pkgs,
  settings,
  ...
}:

{
  imports = [
    # Hardware and system configuration
    ./partitions.nix
    ./hardware-configuration.nix # Generated by installer with actual filesystem mounts

    # Services
    # ./services/cockpit.nix
    # ./services/containers.nix
    # ./services/podman.nix
    # ./services/remote-desktop.nix
  ];

  # System configuration
  networking = {
    hostName = settings.hostName;
    networkmanager.enable = true;
    # hostId = settings.hostId;  # Required for ZFS
  };

  # Boot configuration
  boot.loader = {
    systemd-boot = {
      enable = true;
      # Generate device tree into EFI partition
      extraFiles.${config.hardware.deviceTree.name} =
        "${config.hardware.deviceTree.package}/${config.hardware.deviceTree.name}";
      extraInstallCommands = ''
        mkdir -p /boot/dtb/base
        cp -r ${config.hardware.deviceTree.package}/rockchip/* /boot/dtb/base/
        sync
      '';
    };
    efi = {
      canTouchEfiVariables = true;
      efiSysMountPoint = "/boot/efi";
    };
    timeout = 3;
  };

  # Basic desktop environment for setup
  services.xserver = {
    enable = true;
    desktopManager.xfce.enable = true;
    displayManager.lightdm.enable = true;
  };

  # User configuration
  users.users.${settings.adminUser} = {
    isNormalUser = true;
    hashedPassword = config.sops.secrets."user.hashedPassword".path;
    description = settings.description;
    extraGroups = [
      "wheel"
      "networkmanager"
      "video"
    ];
    openssh.authorizedKeys.keys = settings.sshKeys;
  };

  # Enable SSH access
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
    settings.PermitRootLogin = "no";
  };

  # System packages
  environment.systemPackages = with pkgs; [
    vim
    git
    htop
    tmux
    wget
    curl
    sops
  ];

  system.stateVersion = "25.11";
}
