{
  pkgs,
  lib,
  oc,
  openclawConfig,
  ...
}:
let
  workspaceDefs = import ./workspace {
    inherit lib pkgs;
  };

  tasksDir = "${oc.workspaceDir}/tasks";

  # ── Main agent workspace files ─────────────────────────────
  persistentIntroFile = pkgs.writeText "persistent-intro" workspaceDefs.persistentIntro;
  workspaceDocs = lib.mapAttrs (
    name: doc: pkgs.writeText "${name}-protected" doc.protected
  ) workspaceDefs.documents;
  workspaceDefaults = lib.mapAttrs (
    name: doc: pkgs.writeText "${name}-default" doc.initialPersistent
  ) workspaceDefs.documents;
in
{
  config = {

    systemd.services.docker-openclaw-gateway.serviceConfig = {
      Restart = pkgs.lib.mkForce "always";
      RestartSec = "5s";
    };

    systemd.services.openclaw-setup = {
      description = "Deploy OpenClaw config and secrets";
      wantedBy = [ "multi-user.target" ];
      before = [ "docker-openclaw-gateway.service" ];
      requiredBy = [ "docker-openclaw-gateway.service" ];
      after = [
        "sops-nix.service"
        "openclaw-builder.service"
      ];
      requires = [ "openclaw-builder.service" ];
      serviceConfig.Type = "oneshot";
      script = ''
        set -euo pipefail
        mkdir -p ${oc.configDir} ${oc.workspaceDir}/memory ${oc.workspaceDir}/skills ${oc.workspaceDir}/dropbox

        # Protected+persistent doc assembly
        update_doc_custom() {
          local target="$1"
          local protected_path="$2"
          local default_persistent_path="$3"
          local intro_path="$4"
          local marker="$5"
          local separator=$'\n\n---\n\n'

          if [ -f "$target" ] && grep -Fq "$marker" "$target"; then
             sed -n "/$marker/,\$p" "$target" > "$target.persistent"
          else
             cat "$intro_path" "$default_persistent_path" > "$target.persistent"
          fi

          cat "$protected_path" > "$target.tmp"
          echo "$separator" >> "$target.tmp"
          cat "$target.persistent" >> "$target.tmp"

          mv "$target.tmp" "$target"
          rm -f "$target.persistent"
          chown 1000:1000 "$target"
          chmod 0640 "$target"
        }

        update_doc() {
          update_doc_custom "${oc.workspaceDir}/$1" "$2" "$3" "${persistentIntroFile}" "${workspaceDefs.persistentMarker}"
        }

        update_doc "AGENTS.md" "${workspaceDocs."AGENTS.md"}" "${workspaceDefaults."AGENTS.md"}"
        update_doc "SOUL.md"   "${workspaceDocs."SOUL.md"}"   "${workspaceDefaults."SOUL.md"}"
        update_doc "STYLE.md"  "${workspaceDocs."STYLE.md"}"  "${workspaceDefaults."STYLE.md"}"

        # Lobster tasks deployment
        mkdir -p "${tasksDir}"
        ${lib.concatStringsSep "\n" (
          lib.mapAttrsToList (name: file: ''
            cp ${file} "${tasksDir}/${name}"
          '') workspaceDefs.tasks.templates
        )}
        chown -R 1000:1000 "${tasksDir}"

        # Own everything under configDir before writing the config file
        chown -R 1000:1000 ${oc.configDir}
        chmod -R 700 ${oc.configDir}

        # openclaw.json
        CONFIG_FILE="${oc.configDir}/openclaw.json"
        cp ${openclawConfig.configFile} "$CONFIG_FILE"
        chown 1000:${toString oc.dockerGid} "$CONFIG_FILE"
        chmod 0600 "$CONFIG_FILE"

        # /run/openclaw.env is generated by sops.templates.openclawEnv
      '';
    };

    # Weekly image refresh
    systemd.services.openclaw-refresh = {
      description = "Pull latest OpenClaw image and rebuild custom image";
      serviceConfig.Type = "oneshot";
      script = ''
        ${pkgs.docker}/bin/docker pull ${oc.gatewayBaseImage} || true
        ${pkgs.docker}/bin/docker pull ${oc.sandboxBaseImage} || true
        ${pkgs.docker}/bin/docker image prune -f --filter "until=168h"
        ${pkgs.systemd}/bin/systemctl restart openclaw-builder.service
        ${pkgs.systemd}/bin/systemctl try-restart docker-openclaw-gateway.service
      '';
      after = [ "docker.service" ];
      requires = [ "docker.service" ];
    };

    systemd.timers.openclaw-refresh = {
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnCalendar = "Mon 04:00:00";
        Persistent = true;
        RandomizedDelaySec = "3600";
      };
    };
  };
}
